### ISSUE TITLE
netapp_eseries - check failed - please submit a crash report! (Crash-ID: 5329cb58-455d-11ed-9c16-0242c3cc0745)

### ISSUE THREAD

**Issue by bouncy99** [chexma/checkmk_plugins#3]
Just came across your plugin, and firstly, thank you for both spending the time on this, and sharing it with others.   Unfortunately after installing and discovering services, I was  met with a number of UNKN, with the status detail :-
check failed - please submit a crash report! (Crash-ID: 5329cb58-455d-11ed-9c16-0242c3cc0745)

![netapp plugin errors](https://user-images.githubusercontent.com/65439985/194285848-9adefcce-4ee8-4919-a8b3-3f4c3cd1de51.jpg)
I have also attached a screenshot of what i am seeing. 

I am running the latest plugin from https://exchange.checkmk.com/p/netapp-eseries which shows 2.68, and i am using checkmk :2.1.0p13 in a docker on a QNAP NAS.  Any assistance would be most grateful.

Many thanks.

**Comment by chexma** [comment]
Hi,

happy that you are using my plugins. My E-Mail response seems lost, so i´ll respond here.

Can you try the latest version 2.72 in this repo first ? There was a bug the was explicitly in version 2.1 so please check that first.

**Comment by bouncy99** [comment]
That appears to have resolved the issue, again many thanks, and sorry for
not going to the repo.  You are a life saver to all those who checkmk
appear to have abandoned on santricity models. :)

**Comment by chexma** [comment]
Hi,

 

happy to see that you are using my plugin. Sorry for the problem, its a hobby project and i don´t have so many test systems.

Can you check first if the problem persists with the latest mkp in github ?

Which checkmk version are you using ?

 

https://github.com/chexma/checkmk_plugins/blob/master/netapp_eseries/netapp_eseries-2.72.mkp

 

If that does not work you could send me the output of the datasource program, then i will test against your output:

 

As a site user:

cmk -D <E-Series Hostname in checkmk> | grep Program

 

There is the call to your datasource program, if you execute that, you get the output eg.
 

/omd/sites/<your site name>/local/share/check_mk/agents/special/agent_netappeseries -u 'monitor' -s 'password' 'ip-address'

 

If you redirect that output in a file you can send me that.

 

regards
Andre

 

Gesendet: Donnerstag, 06. Oktober 2022 um 12:07 Uhr
Von: "bouncy99" ***@***.***>
An: "chexma/checkmk_plugins" ***@***.***>
Cc: "Subscribed" ***@***.***>
Betreff: [chexma/checkmk_plugins] netapp_eseries - check failed - please submit a crash report! (Crash-ID: 5329cb58-455d-11ed-9c16-0242c3cc0745) (Issue #3)


 

Just came across your plugin, and firstly, thank you for both spending the time on this, and sharing it with others. Unfortunately after installing and discovering services, I was met with a number of UNKN, with the status detail :-
check failed - please submit a crash report! (Crash-ID: 5329cb58-455d-11ed-9c16-0242c3cc0745)


I have also attached a screenshot of what i am seeing.

I am running the latest plugin from https://exchange.checkmk.com/p/netapp-eseries which shows 2.68, and i am using checkmk :2.1.0p13 in a docker on a QNAP NAS. Any assistance would be most grateful.

Many thanks.

**Comment by bouncy99** [comment]
Good Morning

No need to apologise, i completely understand.  I thought i had already
responded, but i may not have.  Using the updated repo worked a treat and
its all working properly now.

Many thanks for both your integration, and your support.
