### ISSUE TITLE
Netapp E-Series Check in version 2.3

### ISSUE THREAD

**Issue by himself1985** [chexma/checkmk_plugins#9]
I got an error with new version 2.3 if I check plugin from console.

/omd/sites/SITENAME/local/share/check_mk/agents/special/agent_netappeseries -u 'monitor' -s 'PW' -vvv --debug 'IP'
Traceback (most recent call last):
  File "/omd/sites/SITENAME/local/share/check_mk/agents/special/agent_netappeseries", line 29, in <module>
    from cmk.special_agents.utils.agent_common import special_agent_main
ModuleNotFoundError: No module named 'cmk.special_agents.utils.agent_common'

Can you confirm this with version 2.3?

**Comment by chexma** [comment]
Hi,
the plugin is not yet ready for 2.3 but i'm currently rewriting it for the new plugin API.

**Comment by chexma** [comment]
New MKP for 2.3 is uploaded, you might need to recreate the special agent rule.
